# Generated by Django 5.2 on 2025-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['type', 'order', 'name'], 'verbose_name': 'Patrocinador', 'verbose_name_plural': 'Patrocinadores'},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('patrocinador', 'Patrocinador'), ('colaborador', 'Colaborador'), ('medio', 'Blog o Medio')], default='patrocinador', max_length=50, verbose_name='Tipo'),
        ),
    ]
