# Generated by Django 5.2 on 2025-04-20 20:43

import sponsors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsor_options_sponsor_order_sponsor_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Patrocinador', 'verbose_name_plural': 'Patrocinadores'},
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=sponsors.models.sponsor_logo_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
