# Generated by Django 5.2 on 2025-04-19 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='Extracto')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagen')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='Etiquetas')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta descripción')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-date'],
            },
        ),
    ]
