# Generated by Django 5.2 on 2025-04-20 20:43

import blog.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_image_blogimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='is_content_image',
            field=models.BooleanField(default=False, verbose_name='Imagen de contenido'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.post_directory_path, verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta descripción'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL amigable'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, max_length=300, verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
